# Generated by Django 2.0.13 on 2019-05-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myinfo',
            new_name='dbinfo',
        ),
    ]
