# Generated by Django 2.0.13 on 2019-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0002_auto_20190512_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
